name: Update VPNGate Home

on:
  schedule:
    - cron: "0 * * * *"  # her sagatda
  workflow_dispatch:

jobs:
  update-home:
    runs-on: ubuntu-latest
    steps:
      - name: Repo almak
        uses: actions/checkout@v3

      - name: Täze sahypany almak
        run: |
          wget -O home.html https://www.vpngate.net/en/

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add home.html
          git commit -m "Auto update home.html"
          git push
